language: csharp
solution: AutoBuild.sln
install:
    - nuget restore AutoBuild.sln
    - nuget install xunit.runner.console 2.3.1 -OutputDirectory testrunner
script: 
    - xbuild ./:Configuration=Release AutoBuild.sln
    - mono testrunner/xunit.runners.2.3.1/tools/xunit.console.exe AutoBuild.Tests/bin/Debug/AutoBuild.Tests.dll
   