language: csharp
solution: AutoBuild.sln
before_install:
    - nuget apt-get xunit.runner.console -OutputDirectory testrunner
before_script:
    - nuget restore AutoBuild.sln
after_script: 
    - xbuild ./:Configuration=Release AutoBuild.sln
    - xunit.runnerl.console AutoBuild.Tests/bin/Debug/AutoBuild.Tests.dll
   