language: csharp
solution: AutoBuild.sln

install:
    - sudo apt-get install xunit-console
    - nuget restore AutoBuild.sln
script: 
    - xbuild AutoBuild.sln
    - xunit-console AutoBuild.Tests/bin/Debug/AutoBuild.Tests.dll